#!/bin/sh
yum update
yum install git build-essential autoconf libtool openssl-devel gcc -y
cd ~
git clone https://github.com/madeye/shadowsocks-libev.git
cd shadowsocks-libev
./configure
make && make install

